/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zen_lib_terminal_driver_TerminalDriver */

#ifndef _Included_com_zen_lib_terminal_driver_TerminalDriver
#define _Included_com_zen_lib_terminal_driver_TerminalDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    enableRawMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_zen_lib_terminal_driver_TerminalDriver_enableRawMode(JNIEnv*, jclass);

/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    disableRawMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_zen_lib_terminal_driver_TerminalDriver_disableRawMode(JNIEnv*, jclass);

/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_zen_lib_terminal_driver_TerminalDriver_clearScreen(JNIEnv*, jclass);

/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    clearLine
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_zen_lib_terminal_driver_TerminalDriver_clearLine(JNIEnv*, jclass);

/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    gotoxy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zen_lib_terminal_driver_TerminalDriver_gotoxy(
    JNIEnv*, jclass, jint, jint);

/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    getch
 * Signature: (Z)C
 */
JNIEXPORT jchar JNICALL Java_com_zen_lib_terminal_driver_TerminalDriver_getch(
    JNIEnv*, jclass, jboolean);

/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    getTerminalCoordinate
 * Signature: ()Lcom/zen/lib/terminal/driver/TerminalCursorCoordinate;
 */
JNIEXPORT jobject JNICALL
Java_com_zen_lib_terminal_driver_TerminalDriver_getTerminalCursorCoordinate(
    JNIEnv*, jclass);

/*
 * Class:     com_zen_lib_terminal_driver_TerminalDriver
 * Method:    getTerminalWindowSize
 * Signature: ()Lcom/zen/lib/terminal/driver/TerminalWindowSize;
 */
JNIEXPORT jobject JNICALL
Java_com_zen_lib_terminal_driver_TerminalDriver_getTerminalWindowSize(JNIEnv*,
                                                                      jclass);

#ifdef __cplusplus
}
#endif
#endif
